Vagrant.configure("2") do |config|
    [
        { 
            :hostname => 'dockerhost', 
            :ip => '192.168.56.19', 
            :box => 'sbeliakou/centos',
            :ram => "1024" 
        }
    ].each do |node|
        config.vm.define node[:hostname] do |nodeconfig|
            nodeconfig.vm.box = node[:box]
            nodeconfig.vm.hostname = node[:hostname]
            nodeconfig.vm.network :private_network, ip: node[:ip]
            nodeconfig.ssh.insert_key = false
            nodeconfig.vm.provider :virtualbox do |vb|
                vb.name = node[:hostname]
                vb.memory = node[:ram] ? node[:ram].to_s : "512"
                vb.customize ["modifyvm", :id, "--cpuexecutioncap", "20"]
            end
            nodeconfig.vm.provision 'shell', path: "docker.sh"
            nodeconfig.vm.provision 'shell', path: "prometheus.sh"
        end
    end
end