{
 "title": "Docker Engine Native Metrics",
 "description": "Draw docker native metrics",
 "tags": [
  "docker",
  "docker metrics",
  "docker engine"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Docker Info",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "engine_daemon_engine_info",
     "legendFormat": "<p>docker version: {{version}}<p>os: {{os}}<p>kernel: {{kernel}}<p>graphdriver: {{graphdriver}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Number of CPUs",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus" }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "engine_daemon_engine_memory_bytes"
    }
   ]
  },
  {
   "title": "Container States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Number of failed image builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "builder_builds_failed_total", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Number of triggered image builds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "builder_builds_triggered_total" }
   ]
  },
  {
   "title": "Total Container Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Total Network Actions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_network_actions_seconds_count",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}